/****************************************************************************
**
** Copyright (C) 2016 pkzju
**
**
** Version	: 0.1.1.0
** Author	: pkzju
** Website	: https://github.com/pkzju
** Project	: https://github.com/pkzju/QSuperConsole
** 
****************************************************************************/

/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_scanIndexOD (CO_Data* d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data master_Data;
extern INTEGER16 motoRealtimeData[8];		/* Mapped at index 0x2000, subindex 0x01 - 0x08 */
extern INTEGER16 motorSettings[15];		/* Mapped at index 0x2001, subindex 0x01 - 0x0F */
extern INTEGER16 motorPara[4];		/* Mapped at index 0x2002, subindex 0x01 - 0x04 */

#endif // MASTER_H
