
/* File generated by gen_cfile.py. Should not be modified. */

#include "master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER16 motoRealtimeData[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x08 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 motorSettings[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x0F */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 motorPara[] =		/* Mapped at index 0x2002, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 master_iam_a_slave = 0;

TIMER_HANDLE master_heartBeatTimers[32] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 master_obj1000 = 0x0;	/* 0 */
                    subindex master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 master_obj1001 = 0x0;	/* 0 */
                    subindex master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 master_obj1005 = 0x0;	/* 0 */
                    ODCallback_t master_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 master_obj1006 = 0x0;	/* 0 */
                    ODCallback_t master_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 master_obj1014 = 0x80;	/* 128 */
                    subindex master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 master_highestSubIndex_obj1016 = 32; /* number of subindex - 1*/
                    UNS32 master_obj1016[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex master_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[7] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[8] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[9] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[10] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[11] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[12] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[13] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[14] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[15] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[16] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[17] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[18] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[19] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[20] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[21] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[22] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[23] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[24] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[25] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[26] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[27] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[28] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[29] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[30] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1016[31] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 master_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 master_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 master_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 master_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1402_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 master_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 master_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1600[3] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 master_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 master_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 master_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 master_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1602[3] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 master_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 master_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t master_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1800_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 master_highestSubIndex_obj1A00 = 6; /* number of subindex - 1*/
                    UNS32 master_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1A00[5] }
                     };

/* index 0x2000 :   Mapped variable motoRealtimeData */
                    UNS8 master_highestSubIndex_obj2000 = 8; /* number of subindex - 1*/
                    subindex master_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj2000 },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[0] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[1] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[2] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[3] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[4] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[5] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[6] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motoRealtimeData[7] }
                     };

/* index 0x2001 :   Mapped variable motorSettings */
                    UNS8 master_highestSubIndex_obj2001 = 15; /* number of subindex - 1*/
                    subindex master_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj2001 },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[0] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[1] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[2] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[3] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[4] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[5] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[6] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[7] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[8] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[9] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[10] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[11] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[12] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[13] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorSettings[14] }
                     };

/* index 0x2002 :   Mapped variable motorPara */
                    UNS8 master_highestSubIndex_obj2002 = 4; /* number of subindex - 1*/
                    subindex master_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj2002 },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorPara[0] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorPara[1] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorPara[2] },
                       { RW, int16, sizeof (INTEGER16), (void*)&motorPara[3] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable master_objdict[] = 
{
  { (subindex*)master_Index1000,sizeof(master_Index1000)/sizeof(master_Index1000[0]), 0x1000},
  { (subindex*)master_Index1001,sizeof(master_Index1001)/sizeof(master_Index1001[0]), 0x1001},
  { (subindex*)master_Index1005,sizeof(master_Index1005)/sizeof(master_Index1005[0]), 0x1005},
  { (subindex*)master_Index1006,sizeof(master_Index1006)/sizeof(master_Index1006[0]), 0x1006},
  { (subindex*)master_Index1014,sizeof(master_Index1014)/sizeof(master_Index1014[0]), 0x1014},
  { (subindex*)master_Index1016,sizeof(master_Index1016)/sizeof(master_Index1016[0]), 0x1016},
  { (subindex*)master_Index1018,sizeof(master_Index1018)/sizeof(master_Index1018[0]), 0x1018},
  { (subindex*)master_Index1280,sizeof(master_Index1280)/sizeof(master_Index1280[0]), 0x1280},
  { (subindex*)master_Index1400,sizeof(master_Index1400)/sizeof(master_Index1400[0]), 0x1400},
  { (subindex*)master_Index1401,sizeof(master_Index1401)/sizeof(master_Index1401[0]), 0x1401},
  { (subindex*)master_Index1402,sizeof(master_Index1402)/sizeof(master_Index1402[0]), 0x1402},
  { (subindex*)master_Index1600,sizeof(master_Index1600)/sizeof(master_Index1600[0]), 0x1600},
  { (subindex*)master_Index1601,sizeof(master_Index1601)/sizeof(master_Index1601[0]), 0x1601},
  { (subindex*)master_Index1602,sizeof(master_Index1602)/sizeof(master_Index1602[0]), 0x1602},
  { (subindex*)master_Index1800,sizeof(master_Index1800)/sizeof(master_Index1800[0]), 0x1800},
  { (subindex*)master_Index1A00,sizeof(master_Index1A00)/sizeof(master_Index1A00[0]), 0x1A00},
  { (subindex*)master_Index2000,sizeof(master_Index2000)/sizeof(master_Index2000[0]), 0x2000},
  { (subindex*)master_Index2001,sizeof(master_Index2001)/sizeof(master_Index2001[0]), 0x2001},
  { (subindex*)master_Index2002,sizeof(master_Index2002)/sizeof(master_Index2002[0]), 0x2002},
};

const indextable * master_scanIndexOD (CO_Data* d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;

	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1016: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1401: i = 9;break;
		case 0x1402: i = 10;break;
		case 0x1600: i = 11;break;
		case 0x1601: i = 12;break;
		case 0x1602: i = 13;break;
		case 0x1800: i = 14;break;
		case 0x1A00: i = 15;break;
		case 0x2000: i = 16;break;
		case 0x2001: i = 17;break;
		case 0x2002: i = 18;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index master_firstIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  8, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const quick_index master_lastIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  10, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const UNS16 master_ObjdictSize = sizeof(master_objdict)/sizeof(master_objdict[0]); 

CO_Data master_Data = CANOPEN_NODE_DATA_INITIALIZER(master);

