# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\03-开源项目\creat&merge bin\mergeBin.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 124)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 10, 77, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainBinChoseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mainBinChoseBtn.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainBinChoseBtn.setFont(font)
        self.mainBinChoseBtn.setObjectName("mainBinChoseBtn")
        self.verticalLayout.addWidget(self.mainBinChoseBtn)
        self.driveBinChoseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.driveBinChoseBtn.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.driveBinChoseBtn.setFont(font)
        self.driveBinChoseBtn.setObjectName("driveBinChoseBtn")
        self.verticalLayout.addWidget(self.driveBinChoseBtn)
        self.creatBinBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.creatBinBtn.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.creatBinBtn.setFont(font)
        self.creatBinBtn.setObjectName("creatBinBtn")
        self.verticalLayout.addWidget(self.creatBinBtn)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 104))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.mainBinPathText = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.mainBinPathText.setMaximumSize(QtCore.QSize(280, 30))
        self.mainBinPathText.setObjectName("mainBinPathText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mainBinPathText)
        self.driveBinPathText = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.driveBinPathText.setMaximumSize(QtCore.QSize(280, 30))
        self.driveBinPathText.setObjectName("driveBinPathText")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.driveBinPathText)
        self.alignBinText = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.alignBinText.setMaximumSize(QtCore.QSize(280, 30))
        self.alignBinText.setObjectName("alignBinText")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.alignBinText)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainBinChoseBtn.setText(_translate("MainWindow", "浏览"))
        self.driveBinChoseBtn.setText(_translate("MainWindow", "浏览"))
        self.creatBinBtn.setText(_translate("MainWindow", "生成"))
        self.label.setText(_translate("MainWindow", "主板固件："))
        self.label_3.setText(_translate("MainWindow", "固件信息："))
        self.label_4.setText(_translate("MainWindow", "驱动固件："))
