
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaser.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 _valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 _bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 _iam_a_slave = 0;

TIMER_HANDLE _heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 _obj1000 = 0x123456;	/* 1193046 */
                    const CONSTSTORE subindex _Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 _obj1001 = 0x0;	/* 0 */
                    const CONSTSTORE subindex _Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 _highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 _obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t _Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex _Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), .pObject=(void*)&_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), .pObject=(void*)&_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 _obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 _obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 _obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 _obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 _obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 _highestSubIndex_obj1016 = 0;
                    UNS32 _obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 _obj1017 = 1000;	/* 500 */
                    ODCallback_t _Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex _Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 _highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 _obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 _obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 _obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 _obj1018_Serial_Number = 0x0;	/* 0 */
                    const CONSTSTORE subindex _Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 _highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 _obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 _obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    const CONSTSTORE subindex _Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), .pObject=&_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 _obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 _obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 _obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    const CONSTSTORE subindex _Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), .pObject=&_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), .pObject=&_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), .pObject=&_obj1280_Node_ID_of_the_SDO_Server }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const CONSTSTORE indextable _objdict[] = 
{
  { (const CONSTSTORE subindex* const)_Index1000,sizeof(_Index1000)/sizeof(_Index1000[0]), 0x1000},
  { (const CONSTSTORE subindex* const)_Index1001,sizeof(_Index1001)/sizeof(_Index1001[0]), 0x1001},
  { (const CONSTSTORE subindex* const)_Index1017,sizeof(_Index1017)/sizeof(_Index1017[0]), 0x1017},
  { (const CONSTSTORE subindex* const)_Index1018,sizeof(_Index1018)/sizeof(_Index1018[0]), 0x1018},
  { (const CONSTSTORE subindex* const)_Index1200,sizeof(_Index1200)/sizeof(_Index1200[0]), 0x1200},
  { (const CONSTSTORE subindex* const)_Index1280,sizeof(_Index1280)/sizeof(_Index1280[0]), 0x1280},
};

const CONSTSTORE indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = _Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1280: i = 5;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status _PDO_status[1] = {s_PDO_status_Initializer};

const CONSTSTORE quick_index _firstIndex = {
  4, /* SDO_SVR */
  5, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const CONSTSTORE quick_index _lastIndex = {
  4, /* SDO_SVR */
  5, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const CONSTSTORE UNS16 _ObjdictSize = sizeof(_objdict)/sizeof(_objdict[0]); 

CO_Data _Data = CANOPEN_NODE_DATA_INITIALIZER();

