
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaser.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaser_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaser_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaser_iam_a_slave = 0;

TIMER_HANDLE TestMaser_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaser_obj1000 = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaser_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaser_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaser_obj1001 = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaser_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaser_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaser_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaser_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaser_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaser_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), .pObject=(void*)&TestMaser_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), .pObject=(void*)&TestMaser_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestMaser_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestMaser_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaser_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaser_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestMaser_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestMaser_highestSubIndex_obj1016 = 0;
                    UNS32 TestMaser_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestMaser_obj1017 = 1000;	/* 500 */
                    ODCallback_t TestMaser_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const CONSTSTORE subindex TestMaser_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), .pObject=&TestMaser_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestMaser_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaser_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaser_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaser_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaser_obj1018_Serial_Number = 0x0;	/* 0 */
                    const CONSTSTORE subindex TestMaser_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject=&TestMaser_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaser_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaser_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaser_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), .pObject=&TestMaser_obj1018_Serial_Number }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const CONSTSTORE indextable TestMaser_objdict[] = 
{
  { (const CONSTSTORE subindex* const)TestMaser_Index1000,sizeof(TestMaser_Index1000)/sizeof(TestMaser_Index1000[0]), 0x1000},
  { (const CONSTSTORE subindex* const)TestMaser_Index1001,sizeof(TestMaser_Index1001)/sizeof(TestMaser_Index1001[0]), 0x1001},
  { (const CONSTSTORE subindex* const)TestMaser_Index1017,sizeof(TestMaser_Index1017)/sizeof(TestMaser_Index1017[0]), 0x1017},
  { (const CONSTSTORE subindex* const)TestMaser_Index1018,sizeof(TestMaser_Index1018)/sizeof(TestMaser_Index1018[0]), 0x1018},
};

const CONSTSTORE indextable * TestMaser_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = TestMaser_Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaser_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaser_PDO_status[1] = {s_PDO_status_Initializer};

const CONSTSTORE quick_index TestMaser_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const CONSTSTORE quick_index TestMaser_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const CONSTSTORE UNS16 TestMaser_ObjdictSize = sizeof(TestMaser_objdict)/sizeof(TestMaser_objdict[0]); 

CO_Data TestMaser_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaser);

