
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASER_H
#define TESTMASER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 _valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data _Data;

#endif // TESTMASER_H
