
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASER_H
#define TESTMASER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaser_valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * TestMaser_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaser_Data;

#endif // TESTMASER_H
