# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\01-work\Driver\A9D Plus Drive\updateDriveBin\update_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 197)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.directory_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.directory_text.setGeometry(QtCore.QRect(160, 10, 351, 21))
        self.directory_text.setObjectName("directory_text")
        self.maxPosBtn = QtWidgets.QPushButton(self.centralwidget)
        self.maxPosBtn.setGeometry(QtCore.QRect(90, 130, 61, 23))
        self.maxPosBtn.setObjectName("maxPosBtn")
        self.logText = QtWidgets.QTextBrowser(self.centralwidget)
        self.logText.setGeometry(QtCore.QRect(160, 40, 421, 111))
        self.logText.setObjectName("logText")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 160, 521, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.choseBinBtn = QtWidgets.QPushButton(self.centralwidget)
        self.choseBinBtn.setGeometry(QtCore.QRect(520, 10, 61, 23))
        self.choseBinBtn.setObjectName("choseBinBtn")
        self.updateStart = QtWidgets.QPushButton(self.centralwidget)
        self.updateStart.setGeometry(QtCore.QRect(530, 160, 51, 23))
        self.updateStart.setObjectName("updateStart")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 141, 111))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.devNum = QtWidgets.QComboBox(self.groupBox)
        self.devNum.setObjectName("devNum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.devNum)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verNum = QtWidgets.QTextBrowser(self.groupBox)
        self.verNum.setObjectName("verNum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.verNum)
        self.verticalLayout.addLayout(self.formLayout)
        self.openBtn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(9)
        self.openBtn.setFont(font)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout.addWidget(self.openBtn)
        self.minPosBtn = QtWidgets.QPushButton(self.centralwidget)
        self.minPosBtn.setGeometry(QtCore.QRect(10, 130, 61, 23))
        self.minPosBtn.setObjectName("minPosBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.maxPosBtn.setText(_translate("MainWindow", "MAX 位置"))
        self.choseBinBtn.setText(_translate("MainWindow", "选择"))
        self.updateStart.setText(_translate("MainWindow", "更新"))
        self.groupBox.setTitle(_translate("MainWindow", "驱动板"))
        self.label_3.setText(_translate("MainWindow", "设备号"))
        self.label_4.setText(_translate("MainWindow", "版本号"))
        self.openBtn.setText(_translate("MainWindow", "打开"))
        self.minPosBtn.setText(_translate("MainWindow", "归零"))
